import {useEffect,useMemo,useState} from "react";
import {addDoc,collection,doc,getDoc,getDocs,serverTimestamp} from "firebase/firestore";
import {db} from "./firebase";
import {ArrowRight,Instagram,Mail,Menu,MessageCircle,X} from "lucide-react";
const D={portfolioVisible:true,heroNome:"Brenda",heroSobrenome:"Alencar",heroProfissao:"Social Media & Criadora de Conteúdo",heroDescricao:"Transformo ideias em conteúdo com identidade, estratégia e propósito.",sobreTitulo:"Comunicação que aproxima marcas e pessoas.",sobreTexto1:"Sou Brenda Alencar, estudante de Publicidade e Propaganda, Social Media e criadora de conteúdo.",sobreTexto2:"Atuo com gestão de Instagram, criação de artes e vídeos, planejamento e produção de conteúdo.",trabalhosTitulo:"Meus trabalhos",portfolioTitulo:"Projetos que contam histórias.",portfolioDescricao:"Conheça alguns trabalhos e projetos em destaque.",feedbacksTitulo:"O que dizem sobre meu trabalho",orcamentoTitulo:"Vamos transformar suas ideias em conteúdo?",orcamentoDescricao:"Selecione os serviços para receber uma estimativa inicial.",contatoTitulo:"Vamos criar juntos?",contatoDescricao:"Entre em contato e me conte sobre sua ideia.",instagramUrl:"",email:"",rodapeTexto:"Social Media & Criadora de Conteúdo"};
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function App(){const[menu,setMenu]=useState(false),[site,setSite]=useState(D),[services,setServices]=useState([]),[projects,setProjects]=useState([]),[feedbacks,setFeedbacks]=useState([]),[sel,setSel]=useState([]),[form,setForm]=useState({nome:"",whatsapp:"",descricao:""});
useEffect(()=>{(async()=>{try{const[c,s,p,f]=await Promise.all([getDoc(doc(db,"site","config")),getDocs(collection(db,"services")),getDocs(collection(db,"portfolio")),getDocs(collection(db,"feedbacks"))]);if(c.exists())setSite({...D,...c.data()});setServices(s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false));setProjects(p.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false));setFeedbacks(f.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false))}catch(e){console.warn(e)}})()},[]);
const total=useMemo(()=>sel.reduce((n,id)=>n+Number(services.find(x=>x.id===id)?.price||0),0),[sel,services]);
const toggle=id=>setSel(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
const phone=()=>String(import.meta.env.VITE_WHATSAPP_NUMBER||"").replace(/\D/g,"");
async function send(){const chosen=services.filter(x=>sel.includes(x.id));try{await addDoc(collection(db,"orcamentos"),{nome:form.nome,whatsapp:form.whatsapp,descricao:form.descricao,services:chosen.map(x=>({id:x.id,name:x.name,price:Number(x.price||0)})),total,status:"novo",createdAt:serverTimestamp()})}catch(e){console.warn(e)}const text=`Olá! Vim pelo site Publici Karol.\n\n${chosen.map(x=>`• ${x.name} — ${money(x.price)}`).join("\n")}\n\nEstimativa: ${money(total)}\nNome: ${form.nome}`;window.open(`https://wa.me/${phone()}?text=${encodeURIComponent(text)}`,"_blank")}
const custom=()=>window.open(`https://wa.me/${phone()}?text=${encodeURIComponent("Olá! Vim pelo site Publici Karol e gostaria de solicitar um orçamento personalizado.")}`,"_blank");
return <><header className="nav"><a className="brand-logo" href="#home"><img src="/publici-karol-logo.png"/></a><nav className={menu?"links open":"links"}><a href="#sobre">Sobre</a><a href="#trabalhos">Trabalhos</a>{site.portfolioVisible!==false&&<a href="#portfolio">Portfólio</a>}<a href="#feedbacks">Feedbacks</a><a href="#orcamento">Orçamento</a><a href="#contato">Contato</a></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section id="home" className="hero"><div><span className="eyebrow">SOCIAL MEDIA • CONTEÚDO • ESTRATÉGIA</span><h1>{site.heroNome}<br/><em>{site.heroSobrenome}</em></h1><h2>{site.heroProfissao}</h2><p>{site.heroDescricao}</p><a className="btn" href={site.portfolioVisible!==false?"#portfolio":"#trabalhos"}>Conheça meu trabalho <ArrowRight size={18}/></a></div><div className="hero-art"><div className="hero-photo"><img src="/brenda-alencar.png"/></div></div></section>
<section id="sobre" className="section about"><div className="about-photo"><img src="/brenda-alencar.png"/></div><div><span className="eyebrow">SOBRE MIM</span><h2>{site.sobreTitulo}</h2><p>{site.sobreTexto1}</p><p>{site.sobreTexto2}</p></div></section>
<section id="trabalhos" className="section soft"><div className="center"><span className="eyebrow">O QUE EU FAÇO</span><h2>{site.trabalhosTitulo}</h2></div><div className="work-grid">{services.map(x=><article className="work-card" key={x.id}>{x.imageUrl&&<img src={x.imageUrl}/>}<h3>{x.name}</h3><p>{x.description}</p></article>)}</div></section>
{site.portfolioVisible!==false&&<section id="portfolio" className="section"><span className="eyebrow">PORTFÓLIO</span><h2>{site.portfolioTitulo}</h2><p>{site.portfolioDescricao}</p><div className="portfolio-grid">{projects.map(x=><article className="project" key={x.id}><div className="project-image">{x.imageUrl?<img src={x.imageUrl}/>:<span>SEM IMAGEM</span>}</div><small>{x.category}</small><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>}
<section id="feedbacks" className="feedback section"><span className="eyebrow light">FEEDBACKS</span><h2>{site.feedbacksTitulo}</h2><div className="quotes">{feedbacks.map(x=><blockquote key={x.id}>“{x.text}”<footer>— {x.name}{x.role?`, ${x.role}`:""}</footer></blockquote>)}</div></section>
<section id="orcamento" className="section"><div className="center"><span className="eyebrow">ORÇAMENTO</span><h2>{site.orcamentoTitulo}</h2><p>{site.orcamentoDescricao}</p></div><div className="budget-grid"><div className="service-picker">{services.map(x=><label className={sel.includes(x.id)?"service-option active":"service-option"} key={x.id}><input type="checkbox" checked={sel.includes(x.id)} onChange={()=>toggle(x.id)}/><div><strong>{x.name}</strong><small>{x.description}</small></div><b>{Number(x.price)>0?money(x.price):"Sob consulta"}</b></label>)}</div><aside className="summary"><h3>Seu pré-orçamento</h3><div className="total"><span>Estimativa</span><strong>{money(total)}</strong></div><input placeholder="Seu nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input placeholder="Seu WhatsApp" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><textarea placeholder="Conte o que precisa" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/><button className="btn white" disabled={!sel.length} onClick={send}><MessageCircle/>Enviar pelo WhatsApp</button><button className="text-btn" onClick={custom}>Orçamento personalizado</button></aside></div></section>
<section id="contato" className="section contact"><div><span className="eyebrow">CONTATO</span><h2>{site.contatoTitulo}</h2><p>{site.contatoDescricao}</p></div><div className="contact-links"><a href={site.instagramUrl||"#"}><Instagram/>Instagram</a><button onClick={custom}><MessageCircle/>WhatsApp</button><a href={site.email?`mailto:${site.email}`:"#"}><Mail/>E-mail</a></div></section></main>
<footer className="footer"><img src="/publici-karol-logo.png"/><p>{site.rodapeTexto}</p><a href="/admin">Área Administrativa</a></footer></>}
